name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Setup Mise (or directly Rustup) for toolchain management
      - name: Setup Mise
        uses: jdxcode/mise@v1
        with:
          version: 'latest'

      - name: Use project-defined tools with Mise
        run: mise use --install

      - name: Check formatting
        run: make fmt

      - name: Run clippy lints
        run: make lint

      - name: Run tests
        run: make test

      - name: Build project (debug)
        run: make build

      - name: Build project (release)
        run: make release

      # Optional: Run security audit
      - name: Run cargo audit
        run: mise run -- cargo audit --deny warnings || true
        continue-on-error: true